// playground/vite-react/src/Story.jsx
import { getWhyframeSource } from '@whyframe/core/utils'
import { useEffect, useRef, useState } from 'react'

export function Story({ title, src, children }) {
  const iframe = useRef(null)
  const [source, setSource] = useState('')

  useEffect(() => {
    setSource(iframe.current ? getWhyframeSource(iframe.current) : '')
  }, [iframe])

  return (
    <div>
      <p>This is a story of {title}:</p>

      <iframe ref={iframe} data-why title={title} src={src}>
        {children}
      </iframe>

      <details>
        <summary>source</summary>
        <pre>{source}</pre>
      </details>
    </div>
  )
}

// playground/vite-solid/src/Story.jsx
import { getWhyframeSource } from '@whyframe/core/utils'
import { createSignal } from 'solid-js'

export function Story(props) {
  const [source, setSource] = createSignal('')

  return (
    <div>
      <p>This is a story of {props.title}:</p>

      <iframe
        ref={(el) => el && setSource(getWhyframeSource(el))}
        data-why
        title={props.title}
        src={props.src}
      >
        {props.children}
      </iframe>

      <details>
        <summary>source</summary>
        <pre>{source()}</pre>
      </details>
    </div>
  )
}
