// playground/vite-react/src/Counter.jsx
import { useState } from 'react'

export function Counter({ max = 10, onMax }) {
  const [count, setCount] = useState(0)

  const increment = () => {
    if (max !== 0 && count >= max) {
      onMax?.()
      document.body.style.backgroundColor = 'pink'
      alert('too many clicks')
      return
    }
    setCount(count + 1)
  }

  return <button onClick={increment}>count is {count}</button>
}

// playground/vite-svelte/src/Counter.svelte
<script>
  export let max = 0

  let count = 0
  const increment = () => {
    if (max !== 0 && count >= max) {
      document.body.style.backgroundColor = 'pink'
      alert('too many clicks')
      return
    }
    count += 1
  }
</script>

<button on:click={increment}>
  count is {count}
</button>
