// playground/sveltekit/src/lib/Story.svelte
<script>
  import { getWhyframeSource } from '@whyframe/core/utils'

  /** @type {string} */
  export let title
  /** @type {string | undefined} */
  export let src = undefined

  /** @type {HTMLIFrameElement}*/
  let iframe
  $: source = iframe ? getWhyframeSource(iframe) : undefined
</script>

<div>
  <p>
    This is a story of {title}:
  </p>

  <iframe bind:this={iframe} data-why {title} {src}>
    <slot />
  </iframe>

  <details>
    <summary>source</summary>
    <pre>{source}</pre>
  </details>
</div>

// playground/vite-vue/src/Story.vue
<script setup>
import { getWhyframeSource } from '@whyframe/core/utils'
import { computed, ref } from 'vue'

defineProps(['title', 'src'])

const iframe = ref()
const source = computed(() => {
  return iframe.value ? getWhyframeSource(iframe.value) : undefined
})
</script>

<template>
  <div>
    <p>This is a story of {{ title }}:</p>

    <iframe ref="iframe" data-why :title="title" :src="src">
      <slot />
    </iframe>

    <details>
      <summary>source</summary>
      <pre>{{ source }}</pre>
    </details>
  </div>
</template>
